# Generated by Django 5.2.5 on 2025-09-05 14:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='author',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец объявления'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(max_length=8192, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название объявления'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время отзыва')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_feedback', to='ads.advertisement', verbose_name='Объявление, под которым оставлен отзыв')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Владелец отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('owner', 'created_at'),
            },
        ),
    ]
